version: 1.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
build:
  verbosity: minimal
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"tests\Serpentine.IISModule.Tests\bin\%configuration%\Serpentine.IISModule.Tests.dll -noshadow" -filter:"+[Serpentine.IISModule*]* -[Serpentine.IISModule.Tests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
artifacts:
- path: src\Serpentine.IISModule\bin\$(configuration)
  name: Serpentine.IISModule
  type: zip
deploy:
  provider: GitHub
  auth_token:
    secure: s8fov/sET5a7fqyi0ddedgj+iqB6YfodYj0+4ppKBqmldhfqS7yam2mihM9ZsAaZ
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true